---
title: "BRFSS Data"
author: "Ethan Walker"
date: "July 29, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r, echo=FALSE}
library(tidyverse)
```

```{r, echo=FALSE}
# Load databases

# brfss_data <- read_csv("C:/R/Personal_Projects/brfss_data_2017/brfss_data.csv")
# brfss_data <- read_rds("output/brfss_data.rds")

# oregon_brfss_2014 <- read_csv("input/oregon_brfss_2014.csv")
oregon_brfss_2014 <- read_rds("output/oregon_brfss_2014.rds")
```

# Initial look, clean oregon_brfss_2014
```{r}
head(oregon_brfss_2014, 5)

clean_data_oregon <- oregon_brfss_2014 %>% 
  mutate(id = SEQNO,
         age_cat = `@_AGE_G`,
         sex = SEX,
         education_cat = EDUCA,
         employment_cat = EMPLOY1,
         marital_cat = MARITAL,
         veteran = VETERAN3,
         asthma = `@_CASTHM1`,
         pneum_vax = PNEUVAC3,
         smoke_100 = SMOKE100,
         smoke_now = SMOKDAY2,
         tobacco_now = USENOW3,
         current_smoker = `@_RFSMOK3`,
         bmi = `@_BMI5`,
         bmi_cat = `@_BMI5CAT`) %>% 
  select(id, age_cat, sex, education_cat, employment_cat, marital_cat, veteran,
         asthma, pneum_vax, smoke_100, smoke_now, tobacco_now, current_smoker,
         bmi, bmi_cat) %>% 
  mutate(age_cat = factor(age_cat, levels = c(1,2,3,4,5,6),
                          labels = c("18-24", "25-34", "35-44", "45-54", "55-64", "65+")),
         sex = factor(sex, levels = c(1,2), labels = c("male", "female")),
         education_cat = factor(education_cat, levels = c(1,2,3,4,5,6),
                          labels = c("none", "elementary", "some high school", 
                                     "high school grad", "some college", "college grad")),
         employment_cat = factor(employment_cat, levels = c(1,2,3,4,5,6,7,8),
                          labels = c("employed for wages", "self-employed", "out of work 1yr+", 
                                     "out of work <1yr", "homemaker", "student",
                                     "retired", "unable to work")),
         marital_cat = factor(marital_cat, levels = c(1,2,3,4,5,6),
                          labels = c("married", "divorced", "widowed", 
                                     "separated", "never married", "unmarried couple")),
         veteran = factor(veteran, levels = c(1,2), labels = c("yes", "no")),
         asthma = factor(asthma, levels = c(1,2), labels = c("no", "yes")),
         pneum_vax = factor(pneum_vax, levels = c(1,2), labels = c("yes", "no")),
         smoke_100 = factor(smoke_100, levels = c(1,2), labels = c("yes", "no")),
         smoke_now = factor(smoke_now, levels = c(1,2,3), 
                            labels = c("every day", "some days", "not at all")),
         tobacco_now = factor(tobacco_now, levels = c(1,2,3), 
                            labels = c("every day", "some days", "not at all")),
         current_smoker = factor(current_smoker, levels = c(1,2), labels = c("no", "yes")),
         bmi = as.numeric(bmi),
         bmi_cat = factor(bmi_cat, levels = c(1,2,3,4),
                          labels = c("underweight", "normal", "overweight", "obese")))

head(clean_data_oregon, 5)
```

# Check data
## Compare numbers in each factor to make sure levels/NAs were coded correctly
```{r}
table(clean_data_oregon$age_cat)
table(oregon_brfss_2014$`@_AGE_G`)

table(clean_data_oregon$sex)
table(oregon_brfss_2014$SEX)

table(clean_data_oregon$education_cat)
table(oregon_brfss_2014$EDUCA)

table(clean_data_oregon$employment_cat)
table(oregon_brfss_2014$EMPLOY1)

table(clean_data_oregon$marital_cat)
table(oregon_brfss_2014$MARITAL)

table(clean_data_oregon$veteran)
table(oregon_brfss_2014$VETERAN3)

table(clean_data_oregon$asthma)
table(oregon_brfss_2014$`@_CASTHM1`)

table(clean_data_oregon$pneum_vax)
table(oregon_brfss_2014$PNEUVAC3)

table(clean_data_oregon$smoke_100)
table(oregon_brfss_2014$SMOKE100)

table(clean_data_oregon$smoke_now)
table(oregon_brfss_2014$SMOKDAY2)

table(clean_data_oregon$tobacco_now)
table(oregon_brfss_2014$USENOW3)

table(clean_data_oregon$current_smoker)
table(oregon_brfss_2014$`@_RFSMOK3`)

table(clean_data_oregon$bmi_cat)
table(oregon_brfss_2014$`@_BMI5CAT`)
```

# Function for plotting each categorical variable
```{r}
hist_function <- function(df = clean_data_oregon, var) {
hist_plot <- df %>% 
  rename(result = var) %>% 
  ggplot(aes(result)) +
    geom_bar(stat = "count", fill = "steelblue", color = "black") +
    geom_text(stat = "count", aes(label = ..count..), vjust = -0.5, size = 5) +
    ggtitle("Sample of Oregon BRFSS Data from 2014",
            subtitle = "Count data for categorical variables") +
    xlab(var) +
    theme_minimal() +
    scale_y_continuous(expand = expand_scale(add = c(20, 100))) +
    theme(axis.line = element_line(size = 1.2), 
          panel.grid.major.y = element_line(size = 0.5, color = "black"), 
          panel.grid.major.x = element_blank(), 
          axis.text.x = element_text(size = 14, color = "black", angle = 40,
                                     hjust = .9, vjust = .9), 
          axis.text.y = element_text(size = 14, color = "black"), 
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          title = element_text(size = 16, color = "black")) 
hist_plot
}

hist_function(clean_data_oregon, var = "age_cat")
hist_function(clean_data_oregon, var = "sex")
hist_function(clean_data_oregon, var = "education_cat")
hist_function(clean_data_oregon, var = "employment_cat")
hist_function(clean_data_oregon, var = "marital_cat")
hist_function(clean_data_oregon, var = "veteran")
hist_function(clean_data_oregon, var = "asthma")
hist_function(clean_data_oregon, var = "pneum_vax")
hist_function(clean_data_oregon, var = "smoke_100")
hist_function(clean_data_oregon, var = "smoke_now")
hist_function(clean_data_oregon, var = "tobacco_now")
hist_function(clean_data_oregon, var = "current_smoker")
hist_function(clean_data_oregon, var = "bmi_cat")
```



```{r, echo=FALSE, eval=FALSE}
# Initial look, clean brfss_data
head(brfss_data, 10)

clean_data <- brfss_data %>% 
  spread(Question, Data_Value) %>% 
  mutate(year = as.numeric(YearStart),
         state_abb = LocationAbbr,
         state = LocationDesc,
         overweight = 
           `Percent of adults aged 18 years and older who have an overweight classification`,
         obese = 
           `Percent of adults aged 18 years and older who have obesity`,
         aerobic_activity_150_min =
           `Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination)`,
         aerobic_strength_activity_150_min =
           `Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic physical activity and engage in muscle-strengthening activities on 2 or more days a week`,
         aerobic_activity_300_min =
           `Percent of adults who achieve at least 300 minutes a week of moderate-intensity aerobic physical activity or 150 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination)`,
         strength_training_2_days =
           `Percent of adults who engage in muscle-strengthening activities on 2 or more days a week`,
         no_physical_activity =
           `Percent of adults who engage in no leisure-time physical activity`,
         fruit_less_than_daily = 
           `Percent of adults who report consuming fruit less than one time daily`,
         veg_less_than_daily =
           `Percent of adults who report consuming vegetables less than one time daily`) %>% 
  spread(StratificationCategory1, Stratification1) %>% 
  mutate(age_cat = `Age (years)`,
         education = Education,
         gender = Gender,
         income = Income,
         race_eth = `Race/Ethnicity`,
         total = Total,
         cl_low = Low_Confidence_Limit,
         cl_hi = High_Confidence_Limit,
         sample_size = Sample_Size,
         geo_location = GeoLocation) %>% 
  select(year, state, state_abb, overweight, obese, aerobic_activity_150_min,
         aerobic_strength_activity_150_min, aerobic_activity_300_min,
         strength_training_2_days, no_physical_activity, fruit_less_than_daily,
         veg_less_than_daily, age_cat, education, gender, income, race_eth,
         total, cl_low, cl_hi, sample_size, geo_location)

head(clean_data, 10)
```


```{r, echo=FALSE, eval=FALSE}
# Filter and assess data
co_data <- clean_data %>% 
  filter(state_abb == "CO") %>% 
  filter(total == "Total")
```


# Save original data as RDS
```{r, echo=FALSE, eval=FALSE}
saveRDS(brfss_data, "C:/R/Personal_Projects/output/brfss_data.rds")
saveRDS(oregon_brfss_2014, "C:/R/Personal_Projects/output/oregon_brfss_2014.rds")
```