---
title: "Three Oaks Farms Precipitation"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

```{r, message=FALSE, echo=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(forcats)
library(knitr)
library(shiny)
library(rsconnect)
library(plotly)
library(DT)
library(rmarkdown)
```

```{r, message=FALSE, echo=FALSE}
precip_data <- read_csv("input/farm_precip_31dec2020.csv")
```

```{r, echo=FALSE}
# Clean data
precip_clean <- precip_data %>% 
  mutate(date = mdy(date)) %>% 
  mutate(month = month(date, label = TRUE)) %>%
  mutate(year = year(date)) %>%
  mutate(precip_cat = cut(precip, breaks = c(0,.5,1,2,5), 
                               labels = c("<0.5", "0.5 - 0.99", 
                                             "1 - 1.99", "2+"), 
                               right = FALSE)) %>% 
  group_by(month)

summary_data <- precip_data %>%
    mutate(date = mdy(date)) %>% 
    mutate(month = month(date, label = TRUE)) %>%
    mutate(year = year(date)) %>%
    group_by(year, month) %>% 
    summarise(sum(precip), n(), mean(precip), median(precip), max(precip)) %>% 
    rename(Month = month, `Total Precip` = `sum(precip)`, `Precip Events` = `n()`, 
           `Mean Precip Event` = `mean(precip)`, `Median Precip Event` = `median(precip)`, 
           `Max Precip Event` = `max(precip)`) %>% 
    ungroup()
```


```{r, echo=FALSE}
ui <- fluidPage(

  titlePanel(""),

  sidebarLayout(

    sidebarPanel(width = 2,

      selectInput(inputId = "year",
                  label = "Year:",
                  choices = c(2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020))
    ),

    mainPanel(width = 10,
              
      plotlyOutput(outputId = "precip_bar", width = "90%", height = "500px"),
      
      headerPanel("Summary table"),
      
      tableOutput(outputId = "precip_table")

    )
  )
)
```


```{r, echo=FALSE}
server <- function(input, output) {

filtered_data <- reactive({
    precip_clean %>%
    filter(year == input$year)
}) 

output$precip_bar <- renderPlotly({
rain_plot <- ggplot(filtered_data()) +
    geom_col(aes(x = month, y = precip, fill = precip_cat), 
             color = "black") +
    labs(title = "",
         x = "", y = "Precipitation total (inches)") +
    theme_minimal() +
    theme(axis.line = element_line(size = 1.2), 
          panel.grid.major.y = element_line(size = 0.5, color = "black"), 
          panel.grid.major.x = element_blank(), 
          axis.text.x = element_text(size = 12, color = "black", angle = 25), 
          axis.text.y = element_text(size = 12, color = "black"),
          title = element_text(size = 15),
          legend.text = element_text(size = 12),
          panel.spacing.x = unit(5, "cm")) +
    scale_fill_brewer(palette = "Blues")
  ggplotly(rain_plot) %>% 
    layout(legend = list(orientation = "h", x = 0, y = -0.23),
           annotations = list(text="Precipitation category", xref="paper", yref="paper",
                  x=0.0, y=-0.2, legendtitle=TRUE, showarrow=FALSE),
                  font = list(size = 18))
})


table_data <- reactive({
    summary_data %>%
    filter(year == input$year) %>% 
    select(-year) 
})


output$precip_table <- renderTable({
  print(table_data())
})

}
```


```{r, echo=FALSE}
shinyApp(ui, server, options = list(height = 1080))
```