---
title: "Three Oaks Farms Precipitation Trends"
output:
  pdf_document: default
  html_notebook: default
  word_document: default
---

```{r, message=FALSE, echo=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(forcats)
library(knitr)
```

```{r, message=FALSE, echo=FALSE}
precip_data <- read_csv("farm_precip_3march2019.csv")
```

```{r, echo=FALSE}
# Clean data
precip_clean <- precip_data %>% 
  mutate(date = mdy(date)) %>% 
  mutate(month = month(date, label = TRUE)) %>%
  mutate(year = year(date)) %>%
  mutate(precip_cat = cut(precip, breaks = c(0,.5,1,2,5), 
                               labels = c("<0.5", "0.5 - 0.99", 
                                             "1 - 1.99", "2+"), 
                               right = FALSE)) 
```
##Summary Statistics
###Summary by Year
```{r, echo=FALSE}
summary_by_year <- precip_clean %>% 
  group_by(year) %>% 
  summarise(sum(precip), n(), mean(precip), median(precip), max(precip)) %>% 
  rename(Year = year, `Total Precip` = `sum(precip)`, `Precip Events` = `n()`, 
         `Mean Precip Event` = `mean(precip)`, `Median Precip Event` = `median(precip)`, 
         `Max Precip Event` = `max(precip)`)
kable(summary_by_year, digits = 2)
```

###Summary by Month
```{r, echo=FALSE}
summary_by_month <- precip_clean %>% 
  group_by(month) %>% 
  summarise(sum(precip), n(), mean(precip), median(precip), max(precip)) %>% 
  rename(Month = month, `Total Precip` = `sum(precip)`, `Precip Events` = `n()`, 
         `Mean Precip Event` = `mean(precip)`, `Median Precip Event` = `median(precip)`, 
         `Max Precip Event` = `max(precip)`)
kable(summary_by_month, digits = 2)
```

###Summary by Month and Year
```{r, echo=FALSE}
summary_by_month <- precip_clean %>% 
  group_by(year, month) %>% 
  summarise(sum(precip), n(), mean(precip), median(precip), max(precip)) %>% 
  rename(Year = year, Month = month, `Total Precip` = `sum(precip)`, `Precip Events` = `n()`, 
         `Mean Precip Event` = `mean(precip)`, `Median Precip Event` = `median(precip)`, 
         `Max Precip Event` = `max(precip)`)
kable(summary_by_month, digits = 2)
```

###Monthly Averages
```{r, echo=FALSE}
summary_month <- precip_clean %>% 
  group_by(month) %>% 
  mutate(month_sum = sum(precip)) %>% 
  mutate(year = as.character(year)) %>% 
  mutate(year_num = n_distinct(year)) %>% 
  select(month, month_sum, year_num) %>% 
  mutate(month_mean = month_sum / year_num) %>% 
  select(month, month_mean) %>% 
  distinct(month, month_mean) %>% 
  rename(Month = month, `Monthly Average` = month_mean)
kable(summary_month, digits = 2)
```

##Plots
```{r, echo=FALSE, fig.width=10, fig.height=8}
# Bar Plot
precip_bar <- precip_clean %>% 
  group_by(month) %>%
  rename("Precipitation Category" = precip_cat) %>%
  ggplot() +
    geom_col(aes(x = month, y = precip, fill = `Precipitation Category`), 
             color = "black") +
    labs(x = "", y = "Precipitation Total (inches)", 
         title = "Three Oaks Farms Precipitation", 
         subtitle = "Combined Monthly Totals: 2013 - Present") +
    theme_minimal() +
    theme(axis.line = element_line(size = 1.2), 
          panel.grid.major.y = element_line(size = 0.5, color = "black"), 
          panel.grid.major.x = element_blank(), 
          axis.text.x = element_text(size = 8, color = "black", angle = 15), 
          axis.text.y = element_text(size = 14, color = "black"), 
          title = element_text(size = 17, color = "black"), 
          legend.text = element_text(size = 15), 
          legend.position = "right") +
    scale_fill_brewer(palette = "Blues")

precip_bar
```

```{r, echo=FALSE, fig.width=10, fig.height=8}
# Bar Plot
precip_bar_function <- function(df = precip_clean, yr) {
precip_bar <- df %>% 
  filter(year == yr) %>% 
  group_by(month) %>%
  rename("Precipitation Category" = precip_cat) %>% 
  ggplot() +
    geom_col(aes(x = month, y = precip, fill = `Precipitation Category`), 
             color = "black") +
    labs(x = "", y = "Precipitation Total (inches)", 
         title = "Three Oaks Farms Precipitation", 
         subtitle = yr) +
    theme_minimal() +
    theme(axis.line = element_line(size = 1.2), 
          panel.grid.major.y = element_line(size = 0.5, color = "black"), 
          panel.grid.major.x = element_blank(), 
          axis.text.x = element_text(size = 14, color = "black", angle = 15), 
          axis.text.y = element_text(size = 14, color = "black"), 
          title = element_text(size = 17, color = "black"), 
          legend.text = element_text(size = 15)) +
    scale_fill_brewer(palette = "Blues")
precip_bar
}

precip_bar_function(precip_clean, "2013")
precip_bar_function(precip_clean, "2014")
precip_bar_function(precip_clean, "2015")
precip_bar_function(precip_clean, "2016")
precip_bar_function(precip_clean, "2017")
precip_bar_function(precip_clean, "2018")
```

```{r, echo=FALSE, fig.width=10, fig.height=8}
# Bar Plot
precip_bar <- precip_clean %>% 
  group_by(month) %>%
  rename("Precipitation Category" = precip_cat) %>%
  ggplot() +
    geom_col(aes(x = month, y = precip, fill = `Precipitation Category`), 
             color = "black") +
    labs(x = "", y = "Precipitation Total (inches)", 
         title = "Three Oaks Farms Precipitation") +
    theme_minimal() +
    theme(axis.line = element_line(size = 1.2), 
          panel.grid.major.y = element_line(size = 0.5, color = "black"), 
          panel.grid.major.x = element_blank(), 
          axis.text.x = element_text(size = 8, color = "black", angle = 15), 
          axis.text.y = element_text(size = 14, color = "black"), 
          title = element_text(size = 17, color = "black"), 
          legend.text = element_text(size = 15), 
          legend.position = "bottom") +
    scale_fill_brewer(palette = "Blues") +
    facet_wrap(~year)

precip_bar
```

