---
title: "Wilderness Areas"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r, message=FALSE}
library(maptools)
library(ggmap)
library(tidyverse)
library(rgdal)
library(maps)
library(mapdata)
library(plotly)
```

# Load and format original data
```{r}
# original data, now saved and loaded below

# read in 14er info
peaks <- readOGR("input/14er_coordinates.kml")

# format 14er data
peaks <- as.data.frame(peaks)
peaks_data <- peaks %>% 
  rename(name = Name, long = coords.x1, lat = coords.x2)
# saved below to add "summited" variable

###### Wilderness Areas

# read in shape files
shape <- readOGR(dsn = "input/Wilderness_Areas", layer = "Wilderness_Areas_5_31_19")

# format wilderness shape files
# make sure shape file has correct projection saved to it
## from projargs line under "shape" data description
shape_2 <- spTransform(shape, CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +towgs84=0,0,0"))

# format the coordinates
shape_coords <- fortify(shape_2) 

# make id numeric and ad 1 since it starts at 0
coords <- shape_coords %>% 
  mutate(id = as.numeric(id)+1)

# save shape file as dataframe
wilderness <- as.data.frame(shape_2)
# rownames correspond to wilderness id, so turning them into a column
wilderness <- rownames_to_column(wilderness)
# renaming rowname to id to join with coordinates data
wilderness <- wilderness %>% 
  mutate(id = as.numeric(rowname))

joined <- coords %>% 
  # join coordinates with wilderness data
  left_join(wilderness, by = "id")  %>%
  mutate(name = NAME) 

write_rds(joined, "output/wilderness_data.rds")

###### National Forest

# read in shape files
shape <- readOGR(dsn = "input/S_USA.NFSLandUnit", layer = "S_USA.NFSLandUnit")

# format shape files
# make sure shape file has correct projection saved to it
## from projargs line under "shape" data description
shape_2 <- spTransform(shape, 
                       CRS("+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0"))

# format the coordinates
shape_coords <- fortify(shape_2) 

# make id numeric and ad 1 since it starts at 0
coords <- shape_coords %>% 
  mutate(id = as.numeric(id)+1)

# save shape file as dataframe
nfs <- as.data.frame(shape_2)
# rownames correspond to wilderness id, so turning them into a column
nfs <- rownames_to_column(nfs)
# renaming rowname to id to join with coordinates data
nfs <- nfs %>% 
  mutate(id = as.numeric(rowname) + 1)

joined <- coords %>% 
  # join coordinates with wilderness data
  left_join(nfs, by = "id")  %>%
  mutate(name = NFSLANDU_2) 

write_rds(joined, "output/nfs_data.rds")

###### National Parks

# read in shape files
shape <- readOGR(dsn = "input/National_Park_Service__Park_Unit_Boundaries", 
                 layer = "National_Park_Service__Park_Unit_Boundaries")

# format shape files
# make sure shape file has correct projection saved to it
## from projargs line under "shape" data description
shape_2 <- spTransform(shape, 
                       CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

# format the coordinates
shape_coords <- fortify(shape_2) 

# make id numeric and ad 1 since it starts at 0
coords <- shape_coords %>% 
  mutate(id = as.numeric(id)+1)

# save shape file as dataframe
nps <- as.data.frame(shape_2)
# rownames correspond to wilderness id, so turning them into a column
nps <- rownames_to_column(nps)
# renaming rowname to id to join with coordinates data
nps <- nps %>% 
  mutate(id = as.numeric(rowname) + 1)

joined <- coords %>% 
  # join coordinates with wilderness data
  left_join(nps, by = "id")  %>%
  mutate(name = PARKNAME) 

write_rds(joined, "output/nps_data.rds")
```



# Load and format saved data
```{r}
# read in wilderness and 14er names i have been to
wilderness_names_co <- read_csv("input/wilderness_names_co.csv")
peak_names <- read_csv("input/peak_names.csv") %>% 
  arrange(visited)


# load map layers
usa <- map_data("usa")
states <- map_data("state")  %>% 
  filter(region == "colorado")
cities <- maps::us.cities %>% 
  filter(country.etc == "CO") %>% 
  separate(name, c("city"), sep = " CO") %>% 
  filter(city == "Denver" | city == "Fort Collins" | city == "Pueblo" |
         city == "Colorado Springs" | city == "Grand Junction") %>% 
  mutate(capital = factor(capital, levels = c(0,2), labels = c("no", "yes")))

# load shape and point data saved above
wilderness_data <- read_rds("output/wilderness_data.rds") %>% 
  # join with areas i have visited
  left_join(wilderness_names_co, by = "name") %>% 
  filter(STATE == "CO") %>% 
  mutate(type = "Wilderness Area") %>% 
  select(long, lat, order, piece, id, group, name, type, visited)
nfs_data <- read_rds("output/nfs_data.rds") %>% 
  separate(name, c("forest"), sep = " National Forest") %>% 
  filter(forest == "Grand Mesa" | forest == "Arapaho" | forest == "Roosevelt" |
         forest == "Uncompahgre" | forest == "Pike" | forest == "San Isabel" |
         forest == "Routt" | forest == "Gunnison" | forest == "Rio Grande" |
         forest == "San Juan" | forest == "White River") %>% 
  mutate(type = "National Forest",
         name = forest,
         visited = NA) %>% 
  select(long, lat, order, piece, id, group, name, type, visited)
nps_data <- read_rds("output/nps_data.rds") %>% 
  separate(name, c("name"), sep = " National Park") %>% 
  filter(name == "Rocky Mountain" | name == "Great Sand Dunes" |
         name == "Mesa Verde" | name == "Black Canyon of the Gunnison" |
         name == "Dinosaur" | name == "Colorado") %>% 
  mutate(type = "National Park/Monument",
         visited = NA) %>% 
  select(long, lat, order, piece, id, group, name, type, visited)

poly_data <- rbind(wilderness_data, nfs_data, nps_data)

peaks_data <- read_rds("output/peaks_data.rds")
```

# Map the data
```{r}
wilderness_map <- ggplot() + 
  #geom_polygon(data = usa, aes(x=long, y = lat, group = group), 
   #            fill = NA, color = "black") + 
  geom_polygon(data = states, aes(x=long, y = lat, group = group), 
               fill=alpha('lightgreen', 0.15), color = "black", size = 1) + 
  geom_polygon(data = poly_data, aes(x = long, y = lat, group = group,
                                     fill = type, color = visited), 
               size = 0.5) + 
  #geom_polygon(data = nps_data, aes(x = long, y = lat, group = group), 
   #            fill=alpha('gold', 0.5), color = "black", size = 0.25) + 
  #geom_polygon(data = wilderness_data, aes(x = long, y = lat, group = group, 
   #                               color = visited), fill = NA, size = 1) + 
  scale_fill_manual(values=c("lightgreen", "gold", "red")) +
  geom_point(data = cities, aes(x = long, y = lat), size = 2) +
  geom_text(data = cities, aes(x = long, y = lat, label = city), 
            size = 3, hjust = -.15) +
  geom_point(data = peak_names, aes(x = long, y = lat, color = visited), 
             size = 3, shape = 17) +
  scale_color_manual(values=c("black", "blue")) +
  #coord_fixed(1.3)
  coord_map("mercator") +
  ggtitle("Colorado Wilderness Areas and 14ers") +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        legend.position = "right",
        plot.title = element_text(hjust = 0.5))
  

wilderness_map
```

# Save wilderness and 14er names to csv
```{r}
wilderness_names <- joined %>%
  filter(STATE == "CO") %>% 
  select(NAME) %>% 
  unique() %>% 
  mutate(visited = "yes") %>% 
  rename(name = NAME) %>% 
  arrange(name)

write_csv(wilderness_names, "output/wilderness_names_co.csv")


peak_names <- peaks_data %>%
  mutate(visited = "yes") %>% 
  arrange(name)

write_csv(peak_names, "output/peak_names.csv")
```

